name: Release

on:
  push:
    branches:
      - main*

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'protegeproject-bot[bot]' }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.PROTEGEPROJECT_BOT_APP_ID }}
          private-key: ${{ secrets.PROTEGEPROJECT_BOT_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref }}
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: docker.io
          server-username: DOCKER_USERNAME
          server-password: DOCKER_PASSWORD
      - name: Bump version
        id: bump
        uses: mickem/gh-action-bump-maven-version@v1
      - name: Build and Publish package
        run: mvn --batch-mode -Prelease package install
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump.outputs.tag }}
          generate_release_notes: true

env:
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_TOKEN: ${{secrets.DOCKER_PASSWORD}}
